#!/bin/bash

# ----------------------------------------------------------------------------------
# ------------------------ PUT YOUR RUNNING COMMAND(s) HERE ------------------------
# ----------------------------------------------------------------------------------
# ----- This sctipt is executed inside our GPU environment:
# -----     * all output files generated by `build.sh` are placed in this script's workdir
# -----     * feel free to execute `ls` form here to check the content of the workdir
# ----------------------------------------------------------------------------------

# We can see what's on the execution server in the home dir:
echo "Content:"; ls

# # Run binary.
# ./vector_add

# Running diagnostics
# Check if the package is actually installed
pip list | grep flash-attn

# Check where the package files are
pip show flash-attn

# Check if CUDA libraries are visible
ldconfig -p | grep libcuda

# Check CUDA environment
echo $CUDA_HOME
echo $LD_LIBRARY_PATH

# Run the reference FlashAttention benchmark
echo "Running example FlashAttention benchmark"
cd benchmarks/
python3 benchmark_flash_attention.py
